import { NextRequest, NextResponse } from "next/server";

const AVATAR_PROMPT = `Transform this photo into a cute, friendly cartoon avatar in Bitmoji/Snapchat avatar style.
Make it look like a charming illustrated character with:
- Soft, smooth skin with a warm, friendly appearance
- Big expressive eyes with a cute, approachable look
- Simplified but recognizable facial features from the original photo
- Clean vector-art style illustration
- Bright, cheerful colors
- Rounded, friendly shapes
- Professional cartoon illustration quality
Keep the person's likeness clearly recognizable but stylized as a cute cartoon avatar. Make it look like a premium Bitmoji-style personal avatar.`;

export async function POST(request: NextRequest) {
  try {
    const { image } = await request.json();

    if (!image) {
      return NextResponse.json({ error: "No image provided" }, { status: 400 });
    }

    const GEMINI_API_KEY = process.env.GEMINI_API_KEY;
    if (!GEMINI_API_KEY) {
      console.error("GEMINI_API_KEY is not configured");
      return NextResponse.json(
        { error: "Gemini API key not configured. Set GEMINI_API_KEY in .env.local" },
        { status: 500 }
      );
    }

    // Extract base64 data from data URL
    const base64Match = image.match(/^data:image\/\w+;base64,(.+)$/);
    if (!base64Match) {
      return NextResponse.json(
        { error: "Invalid image format. Expected base64 data URL." },
        { status: 400 }
      );
    }
    const base64Data = base64Match[1];
    const mimeType = image.match(/^data:(image\/\w+);base64/)?.[1] || "image/jpeg";

    console.log("Generating avatar with Google Gemini...");

    // Call Google Gemini API
    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-exp-image-generation:generateContent?key=${GEMINI_API_KEY}`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          contents: [
            {
              parts: [
                { text: AVATAR_PROMPT },
                { inline_data: { mime_type: mimeType, data: base64Data } },
              ],
            },
          ],
          generationConfig: { responseModalities: ["TEXT", "IMAGE"] },
        }),
      }
    );

    if (!response.ok) {
      const errorText = await response.text();
      console.error("Gemini API error:", response.status, errorText);

      if (response.status === 429) {
        return NextResponse.json(
          { error: "Rate limit exceeded. Please try again in a moment." },
          { status: 429 }
        );
      }

      return NextResponse.json(
        { error: `Gemini API error: ${response.status}` },
        { status: 500 }
      );
    }

    const data = await response.json();
    console.log("Gemini response received");

    // Extract image from Gemini response
    const parts = data.candidates?.[0]?.content?.parts || [];
    let generatedImageBase64 = null;
    let textResponse = "";

    for (const part of parts) {
      if (part.inline_data?.data) {
        const imgMime = part.inline_data.mime_type || "image/png";
        generatedImageBase64 = `data:${imgMime};base64,${part.inline_data.data}`;
      }
      if (part.text) {
        textResponse = part.text;
      }
    }

    if (!generatedImageBase64) {
      console.error("No image in Gemini response:", JSON.stringify(data));
      return NextResponse.json(
        { error: "No image generated by Gemini" },
        { status: 500 }
      );
    }

    console.log("Avatar generated successfully");

    return NextResponse.json({
      image: generatedImageBase64,
      message: textResponse || "Your digital avatar is ready!",
    });
  } catch (error) {
    console.error("Error in generate-avatar:", error);
    return NextResponse.json(
      { error: error instanceof Error ? error.message : "Unknown error occurred" },
      { status: 500 }
    );
  }
}
