const express = require('express');
const cors = require('cors');
require('dotenv').config();

const app = express();
const PORT = process.env.PORT || 5000;

// Middleware
app.use(cors());
app.use(express.json({ limit: '50mb' }));

const AVATAR_PROMPT = `Transform this photo into a cute, friendly cartoon avatar in Bitmoji/Snapchat avatar style.
Make it look like a charming illustrated character with:
- Soft, smooth skin with a warm, friendly appearance
- Big expressive eyes with a cute, approachable look
- Simplified but recognizable facial features from the original photo
- Clean vector-art style illustration
- Bright, cheerful colors
- Rounded, friendly shapes
- Professional cartoon illustration quality
Keep the person's likeness clearly recognizable but stylized as a cute cartoon avatar. Make it look like a premium Bitmoji-style personal avatar.`;

// POST /generate-avatar
app.post('/generate-avatar', async (req, res) => {
  try {
    const { image } = req.body;

    if (!image) {
      return res.status(400).json({ error: 'No image provided' });
    }

    const GEMINI_API_KEY = process.env.GEMINI_API_KEY;
    if (!GEMINI_API_KEY) {
      console.error('GEMINI_API_KEY is not configured');
      return res.status(500).json({ error: 'Gemini API key not configured. Set GEMINI_API_KEY in server/.env' });
    }

    // Extract base64 data from data URL
    const base64Match = image.match(/^data:image\/\w+;base64,(.+)$/);
    if (!base64Match) {
      return res.status(400).json({ error: 'Invalid image format. Expected base64 data URL.' });
    }
    const base64Data = base64Match[1];
    const mimeType = image.match(/^data:(image\/\w+);base64/)?.[1] || 'image/jpeg';

    console.log('Generating avatar with Google Gemini...');

    // Call Google Gemini API
    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-exp-image-generation:generateContent?key=${GEMINI_API_KEY}`,
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          contents: [
            {
              parts: [
                { text: AVATAR_PROMPT },
                { inline_data: { mime_type: mimeType, data: base64Data } }
              ]
            }
          ],
          generationConfig: { responseModalities: ['TEXT', 'IMAGE'] }
        }),
      }
    );

    if (!response.ok) {
      const errorText = await response.text();
      console.error('Gemini API error:', response.status, errorText);

      if (response.status === 429) {
        return res.status(429).json({ error: 'Rate limit exceeded. Please try again in a moment.' });
      }

      return res.status(500).json({ error: `Gemini API error: ${response.status}` });
    }

    const data = await response.json();
    console.log('Gemini response received');

    // Extract image from Gemini response
    const parts = data.candidates?.[0]?.content?.parts || [];
    let generatedImageBase64 = null;
    let textResponse = '';

    for (const part of parts) {
      if (part.inline_data?.data) {
        const imgMime = part.inline_data.mime_type || 'image/png';
        generatedImageBase64 = `data:${imgMime};base64,${part.inline_data.data}`;
      }
      if (part.text) {
        textResponse = part.text;
      }
    }

    if (!generatedImageBase64) {
      console.error('No image in Gemini response:', JSON.stringify(data));
      return res.status(500).json({ error: 'No image generated by Gemini' });
    }

    console.log('Avatar generated successfully');

    res.json({
      image: generatedImageBase64,
      message: textResponse || 'Your digital avatar is ready!'
    });

  } catch (error) {
    console.error('Error in generate-avatar:', error);
    res.status(500).json({ error: error.message || 'Unknown error occurred' });
  }
});

// Health check
app.get('/health', (req, res) => {
  res.json({ status: 'ok' });
});

app.listen(PORT, () => {
  console.log(`Server running at http://localhost:${PORT}`);
});
