import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

const AVATAR_PROMPT = `Transform this photo into a cute, friendly cartoon avatar in Bitmoji/Snapchat avatar style.
Make it look like a charming illustrated character with:
- Soft, smooth skin with a warm, friendly appearance
- Big expressive eyes with a cute, approachable look
- Simplified but recognizable facial features from the original photo
- Clean vector-art style illustration
- Bright, cheerful colors
- Rounded, friendly shapes
- Professional cartoon illustration quality
Keep the person's likeness clearly recognizable but stylized as a cute cartoon avatar. Make it look like a premium Bitmoji-style personal avatar.`;

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { image } = await req.json();
    
    if (!image) {
      console.error("No image provided in request");
      return new Response(
        JSON.stringify({ error: "No image provided" }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Use your own Google Gemini API key
    const GEMINI_API_KEY = Deno.env.get('GOOGLE_GEMINI_API_KEY');
    if (!GEMINI_API_KEY) {
      console.error("GOOGLE_GEMINI_API_KEY is not configured");
      return new Response(
        JSON.stringify({ error: "Google Gemini API key not configured. Set GOOGLE_GEMINI_API_KEY environment variable." }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    console.log("Generating avatar with Google Gemini...");

    // Extract base64 data from data URL
    const base64Match = image.match(/^data:image\/\w+;base64,(.+)$/);
    if (!base64Match) {
      return new Response(
        JSON.stringify({ error: "Invalid image format. Expected base64 data URL." }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }
    const base64Data = base64Match[1];
    const mimeType = image.match(/^data:(image\/\w+);base64/)?.[1] || "image/jpeg";

    // Call Google Gemini API directly
    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-exp-image-generation:generateContent?key=${GEMINI_API_KEY}`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          contents: [
            {
              parts: [
                { text: AVATAR_PROMPT },
                {
                  inline_data: {
                    mime_type: mimeType,
                    data: base64Data
                  }
                }
              ]
            }
          ],
          generationConfig: {
            responseModalities: ["TEXT", "IMAGE"]
          }
        }),
      }
    );

    if (!response.ok) {
      const errorText = await response.text();
      console.error("Gemini API error:", response.status, errorText);
      
      if (response.status === 429) {
        return new Response(
          JSON.stringify({ error: "Rate limit exceeded. Please try again in a moment." }),
          { status: 429, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
        );
      }
      
      return new Response(
        JSON.stringify({ error: `Gemini API error: ${response.status}` }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const data = await response.json();
    console.log("Gemini response received");

    // Extract image from Gemini response
    const parts = data.candidates?.[0]?.content?.parts || [];
    let generatedImageBase64 = null;
    let textResponse = "";

    for (const part of parts) {
      if (part.inline_data?.data) {
        const imgMime = part.inline_data.mime_type || "image/png";
        generatedImageBase64 = `data:${imgMime};base64,${part.inline_data.data}`;
      }
      if (part.text) {
        textResponse = part.text;
      }
    }
    
    if (!generatedImageBase64) {
      console.error("No image in Gemini response:", JSON.stringify(data));
      return new Response(
        JSON.stringify({ error: "No image generated by Gemini" }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    console.log("Avatar generated successfully");

    return new Response(
      JSON.stringify({ 
        image: generatedImageBase64,
        message: textResponse || "Your digital avatar is ready!"
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (error) {
    console.error("Error in generate-avatar function:", error);
    return new Response(
      JSON.stringify({ error: error instanceof Error ? error.message : "Unknown error occurred" }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});
